org: nikso
app: proma
service: proma-app

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  profile: nikso-proma
  region: ${opt:region, 'eu-west-1'}
  stage: ${opt:stage, 'dev'}
  lambdaHashingVersion: 20201221
  apiGateway:
    shouldStartNameWithService: true
    binaryMediaTypes:
      - '*/*'

package:
  individually: true
  exclude:
    - ./**
  include:
    - build/**

plugins:
  - serverless-offline # serverless-offline needs to be last in the list

functions:
  server:
    name: svelte-server-${self:provider.stage}
    description: Serves Svelte website using Polka serverless.
    handler: build/serverless.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}
